// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPer8x5loAEfaQ_Ibkj8PgrK1MYCBwke0',
    appId: '1:675523411455:web:f32673651ff4ea66b63bca',
    messagingSenderId: '675523411455',
    projectId: 'fish-feeder-app-7a246',
    authDomain: 'fish-feeder-app-7a246.firebaseapp.com',
    storageBucket: 'fish-feeder-app-7a246.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB71uOhWBGdSPE6RBcAkx3TTeqe8_2Nzgk',
    appId: '1:675523411455:android:0aad51c4b9847ce5b63bca',
    messagingSenderId: '675523411455',
    projectId: 'fish-feeder-app-7a246',
    storageBucket: 'fish-feeder-app-7a246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO15OQ3ygp-nKIa03Av-pMPmpHA63iUNc',
    appId: '1:675523411455:ios:4bbd7244261affc9b63bca',
    messagingSenderId: '675523411455',
    projectId: 'fish-feeder-app-7a246',
    storageBucket: 'fish-feeder-app-7a246.firebasestorage.app',
    iosBundleId: 'com.example.fishFeederMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO15OQ3ygp-nKIa03Av-pMPmpHA63iUNc',
    appId: '1:675523411455:ios:4bbd7244261affc9b63bca',
    messagingSenderId: '675523411455',
    projectId: 'fish-feeder-app-7a246',
    storageBucket: 'fish-feeder-app-7a246.firebasestorage.app',
    iosBundleId: 'com.example.fishFeederMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPer8x5loAEfaQ_Ibkj8PgrK1MYCBwke0',
    appId: '1:675523411455:web:7274940691be6192b63bca',
    messagingSenderId: '675523411455',
    projectId: 'fish-feeder-app-7a246',
    authDomain: 'fish-feeder-app-7a246.firebaseapp.com',
    storageBucket: 'fish-feeder-app-7a246.firebasestorage.app',
  );
}
